name: Deploy Angular App to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Firebase CLI globally
        run: npm install -g firebase-tools@12.9.1

      - name: Setup Angular CLI globally
        run: npm install -g @angular/cli@15.1.6

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular App
        run: ng build

      - name: Deploy Angular App to Firebase Hosting
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
